name: Bump downstreams

on:
  push

jobs:
  bump-setup-clojure-lsp:
    name: Bump setup-clojure-lsp Github Action
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Update version in files
        env:
          VERSION: ${{ steps.latest-tag.outputs.tag }}
        run: |
          git config --global user.name "Clojure LSP Bot"
          git config --global user.email "ercdll1337+clojure-lsp@gmail.com"
          mkdir ~/.ssh && touch ~/.ssh/id_rsa
          echo "${{ secrets.CLOJURE_LSP_BOT_COMMIT_TOKEN }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          git clone git@github.com:clojure-lsp/setup-clojure-lsp.git
          cd setup-clojure-lsp
          sed -i "s/clojure-lsp-version: .*/clojure-lsp-version: ${{ env.VERSION }}/g" README.md .github/workflows/self_check.yml .github/workflows/main.yml
          git add README.md .github/workflows/self_check.yml .github/workflows/main.yml
          git commit -m "Bump to version: ${{ env.VERSION }}"
          git push

  bump-lein-clojure-lsp:
    name: Bump lein-clojure-lsp
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Install Babashka
        run: curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install | sudo bash

      - name: Update version in files
        env:
          VERSION: ${{ steps.latest-tag.outputs.tag }}
        run: |
          git config --global user.name "Clojure LSP Bot"
          git config --global user.email "ercdll1337+clojure-lsp@gmail.com"
          mkdir ~/.ssh && touch ~/.ssh/id_rsa
          echo "${{ secrets.CLOJURE_LSP_BOT_COMMIT_TOKEN }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          git clone git@github.com:clojure-lsp/lein-clojure-lsp.git
          cd lein-clojure-lsp
          bb tag-patch-for-version "${{ env.VERSION }}"
