name: Release

on:
  push:
    tags:
      - 2*

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/2')
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latest-tag.outputs.tag}}
          release_name: ${{ steps.latest-tag.outputs.tag}}

  build-jvm:
    name: Build JVM jar and embedded jar
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.5

      - name: Generate jar and embedded jar
        run: lein with-profiles +native-image bin

      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          path: target/clojure-lsp-${{ steps.latest-tag.outputs.tag}}-standalone.jar
          name: clojure-lsp.jar

      - name: Upload embedded jar
        uses: actions/upload-artifact@v2
        with:
          path: target/clojure-lsp
          name: clojure-lsp

  deploy-jvm:
    name: Deploy JVM jar and embedded jar
    needs: build-jvm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -lR

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: clojure-lsp.jar/clojure-lsp-${{ steps.latest-tag.outputs.tag}}-standalone.jar
          asset_name: clojure-lsp.jar
          tag: ${{ steps.latest-tag.outputs.tag}}

      - name: Upload JVM unix embbeded jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: clojure-lsp/clojure-lsp
          asset_name: clojure-lsp
          tag: ${{ steps.latest-tag.outputs.tag}}

      - name: Upload JVM Windows embedded jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: clojure-lsp/clojure-lsp
          asset_name: clojure-lsp.bat
          tag: ${{ steps.latest-tag.outputs.tag}}

  deploy-native-linux:
    name: Deploy native linux binary
    needs: build-jvm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: clojure-lsp.jar

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Install native-image component
        run: |
          gu install native-image

      - name: Build Linux native image
        run: |
          export CLOJURE_LSP_JAR=clojure-lsp.jar
          export CLOJURE_LSP_XMX="-J-Xmx6g"
          graalvm/native-compile.sh

      - uses: papeloto/action-zip@v1
        with:
          files: clojure-lsp
          dest: clojure-lsp-native-linux-amd64.zip

      - name: Upload native image to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: clojure-lsp-native-linux-amd64.zip
          asset_name: clojure-lsp-native-linux-amd64.zip
          tag: ${{ steps.latest-tag.outputs.tag }}

  deploy-native-mac:
    name: Deploy native MacOS binary
    needs: build-jvm
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: clojure-lsp.jar

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.5

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Install native-image component
        run: |
          gu install native-image

      - name: Build MacOS native image
        run: |
          export CLOJURE_LSP_JAR=clojure-lsp.jar
          export CLOJURE_LSP_XMX="-J-Xmx6g"
          graalvm/native-compile.sh

      - uses: papeloto/action-zip@v1
        with:
          files: clojure-lsp
          dest: clojure-lsp-native-macos-amd64.zip

      - name: Upload native image to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: clojure-lsp-native-macos-amd64.zip
          asset_name: clojure-lsp-native-macos-amd64.zip
          tag: ${{ steps.latest-tag.outputs.tag}}
